"""create user table

Revision ID: 263831c8d068
Revises: f590b4e73af8
Create Date: 2025-08-05 11:12:29.169454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263831c8d068'
down_revision: Union[str, Sequence[str], None] = 'f590b4e73af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_info', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.add_column('code_info', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_info', 'is_active')
    op.drop_column('code_info', 'sort_order')
    # ### end Alembic commands ###
