"""modify code tables

Revision ID: 7f6da25e8acb
Revises: 263831c8d068
Create Date: 2025-08-05 11:18:30.168839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6da25e8acb'
down_revision: Union[str, Sequence[str], None] = '263831c8d068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_info', sa.Column('info_code', sa.String(), nullable=False))
    op.add_column('user_info_template', sa.Column('info_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info_template', 'info_name')
    op.drop_column('code_info', 'info_code')
    # ### end Alembic commands ###
