"""create user table

Revision ID: f590b4e73af8
Revises: 
Create Date: 2025-08-05 10:46:08.248304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f590b4e73af8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('room_title', sa.String(), nullable=False),
    sa.Column('user_no', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('user_info_template',
    sa.Column('info_key', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('info_key')
    )
    op.create_table('code_info',
    sa.Column('info_key', sa.String(), nullable=False),
    sa.Column('info_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['info_key'], ['user_info_template.info_key'], ),
    sa.PrimaryKeyConstraint('info_key', 'info_value')
    )
    op.create_table('room_contract_info',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('contract_detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.room_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('room_user_info',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('info_key', sa.String(), nullable=False),
    sa.Column('info_value', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.room_id'], ),
    sa.PrimaryKeyConstraint('room_id', 'info_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_user_info')
    op.drop_table('room_contract_info')
    op.drop_table('code_info')
    op.drop_table('user_info_template')
    op.drop_table('chat_room')
    # ### end Alembic commands ###
